# Use the official Node.js image as a base
FROM node:18.16.0

# Set the working directory
WORKDIR /usr/src/app


RUN npm uninstall bcrypt && npm install bcrypt --save

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install --save

# Copy the rest of your application code
COPY . .
 
# Expose the port the app runs on
EXPOSE 3000

# Command to run the app
CMD ["node", "index.js"]
