apiVersion: apps/v1
kind: Pod
metadata:
  name: nodejs-pod
spec:
  containers:
  - name: nodejs-container
    image: 975050143217.dkr.ecr.ap-southeast-1.amazonaws.com/dental:v1.0
    ports:
    - containerPort: 3000
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "3000"