apiVersion: v1
kind: Pod
metadata:
  name: monfortedental-server-pod
  labels:
    app: monfortedental-server
spec:
  containers:
  - name: monfortedental-server
    image: 975050143217.dkr.ecr.ap-southeast-1.amazonaws.com/monfortedental_server:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    env:
    - name: NODE_ENV
      value: "production"
    - name: PORT
      value: "80"
