apiVersion: apps/v1
kind: Service
metadata:
  name: nodejs-svc
spec:
  selector:
    app: nodejs
  type: LoadBalancer
  ports:
  - protocol: TCP  
    port: 5000
    targetPort: 3000
    nodePort: 31110